services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  roach1:
    image: cockroachdb/cockroach:v23.2.0
    container_name: roach1
    restart: unless-stopped
    command: start --insecure --store=type=mem,size=1GiB --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=roach1,roach2,roach3
    ports:
      - "26257:26257"
      - "8080:8080"

  roach2:
    image: cockroachdb/cockroach:v23.2.0
    container_name: roach2
    restart: unless-stopped
    command: start --insecure --store=type=mem,size=1GiB --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8081 --join=roach1,roach2,roach3

  roach3:
    image: cockroachdb/cockroach:v23.2.0
    container_name: roach3
    restart: unless-stopped
    command: start --insecure --store=type=mem,size=1GiB --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8082 --join=roach1,roach2,roach3

  roach-init:
    image: cockroachdb/cockroach:v23.2.0
    container_name: roach-init
    command: init --insecure --host=roach1:26257
    restart: on-failure
    depends_on:
      - roach1
      - roach2
      - roach3

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - FLOWS=/data_central/flows.json
    volumes:
      - nodered_data:/data
      - .:/data_central
    depends_on:
      - mosquitto
      - roach1

  central:
    build: .
    container_name: central
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_started
      roach-init:
        condition: service_completed_successfully
    environment:
      BROKER_HOST: mosquitto
      BROKER_PORT: 1883
      DB_HOST: roach1
      DB_PORT: 26257
      DB_USER: root
      DB_PASS: ""
      DB_NAME: defaultdb
      PYTHONUNBUFFERED: 1

volumes:
  nodered_data: